version: "2.2"
services:

  es-master03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es-master03
    environment:
      - cluster.name=my-app
      - node.name=es-master03

      - node.master=true
      - node.voting_only=false
      - node.data=false
      - node.ingest=false
      - node.ml=false
      - xpack.ml.enabled=false
      - cluster.remote.connect=false

      - network.host=0.0.0.0

      - discovery.seed_hosts=es-master01,es-master02
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03

      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - ./data:/data

      # elasticsearch data
      - /esdata/master03:/usr/share/elasticsearch/data
      - /eslogs/master03:/usr/share/elasticsearch/logs

    networks:
      - esnet

networks:
  esnet:
    driver: overlay
